name: publish-monaco-editor-core-to-npmjs.org
on:
  push:
    branches:
      - monaco-editor-core-publish
env:
  NODE_OPTIONS: --max-old-space-size=8192
jobs:
  linux:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      # should be aligned with https://github.com/microsoft/vscode/blob/8031c495a65de120560d27703c415eb44c3a99a1/.github/workflows/ci.yml#L22-L32
      - run: |
          sudo ls -a
          sudo apt-get update
          sudo apt-get install -y libxkbfile-dev pkg-config libsecret-1-dev libxss1 dbus xvfb libgtk-3-0
          sudo cp vscode/build/azure-pipelines/linux/xvfb.init /etc/init.d/xvfb
          sudo chmod +x /etc/init.d/xvfb
          sudo update-rc.d xvfb defaults
          sudo service xvfb start
        name: Setup Build Environment
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: yarn
        name: Install dependencies
      - run: gulp editor-distro
        name: Prepare distribution
      - run: cd out-monaco-editor-core
        name: Change to "out-monaco-editor-core" directory
      - run: npm publish
        name: Publish to NPM
